puppetlabs/marionette-collective

.rubocop.yml
Gemfile
Rakefile
lib/mcollective/matcher/scanner.rb
plugins/mcollective/application/plugin.rb

Here we:
Make the exitcode of `rake rubocop` meaningful
Pin rubocop to 0.28.x
Update rules/exceptions to handle the newer cops in rubocop 0.28

MCO-519 rake rubocop should indicate success via exitcode

---

plugins/mcollective/application/facts.rb

Here we check first to see if we have fact values to report on, before attempting to process them.

MCO-558 `mco facts` stacktrace with no found fact

---

Gemfile
Rakefile

Previously MCO didn't have a ci:spec task. This adds the one from puppet, hiera, facter.... (the ci:spec task runs the specs and leaves a junit formatted result.xml in the project root for Jenkins)

(maint) Add ci:spec task from facter/puppet/hiera

---

website/plugin_directory/agent_file_manager.markdown
website/plugin_directory/agent_iptables_junk_filter.markdown
website/plugin_directory/agent_metadata.markdown
website/plugin_directory/agent_registration_mongodb.markdown
website/plugin_directory/agent_registration_monitor.markdown
website/plugin_directory/apt.markdown
website/plugin_directory/authorization_action_policy.markdown
website/plugin_directory/central_rpc_log.markdown
website/plugin_directory/discovery_assisted_ssh.markdown
website/plugin_directory/facter.markdown
website/plugin_directory/facter_via_yaml.markdown
website/plugin_directory/index.markdown
website/plugin_directory/logstash_rpc_audit_logs.markdown
website/plugin_directory/net_test.markdown
website/plugin_directory/none.markdown
website/plugin_directory/nrpe_agent.markdown
website/plugin_directory/ohai.markdown
website/plugin_directory/package.markdown
website/plugin_directory/packages.markdown
website/plugin_directory/process_management.markdown
website/plugin_directory/puppet_agent.markdown
website/plugin_directory/puppet_ca.markdown
website/plugin_directory/puppet_commander.markdown
website/plugin_directory/registration_metadata.markdown
website/plugin_directory/resources_data_plugin.markdown
website/plugin_directory/services.markdown
website/plugin_directory/spamassassin.markdown
website/plugin_directory/stomp_util.markdown
website/plugin_directory/sysctl_data.markdown

This commit provides a new directory for the plugins previously hosted on the Redmine wiki.
There may be some issues with formatting, but we need to move ahead with the migration to expedite the wiki content migration.

Content migration: Moves wiki plugin directory to MCO docs

---

website/plugin_directory/agent_file_manager.markdown
website/plugin_directory/agent_iptables_junk_filter.markdown
website/plugin_directory/agent_metadata.markdown
website/plugin_directory/agent_registration_mongodb.markdown
website/plugin_directory/agent_registration_monitor.markdown
website/plugin_directory/apt.markdown
website/plugin_directory/authorization_action_policy.markdown
website/plugin_directory/central_rpc_log.markdown
website/plugin_directory/facter.markdown
website/plugin_directory/facter_via_yaml.markdown
website/plugin_directory/logstash_rpc_audit_logs.markdown
website/plugin_directory/net_test.markdown
website/plugin_directory/none.markdown
website/plugin_directory/nrpe_agent.markdown
website/plugin_directory/ohai.markdown
website/plugin_directory/package.markdown
website/plugin_directory/packages.markdown
website/plugin_directory/process_management.markdown
website/plugin_directory/puppet_agent.markdown
website/plugin_directory/puppet_ca.markdown
website/plugin_directory/puppet_commander.markdown
website/plugin_directory/registration_metadata.markdown
website/plugin_directory/resources_data_plugin.markdown
website/plugin_directory/services.markdown
website/plugin_directory/spamassassin.markdown
website/plugin_directory/stomp_util.markdown

It should be `template: default`, not `template: normal`. The pages still render, this just makes sure they have a template.

Fix: Replaces erroneous template name with correct one.

---

lib/mcollective/config.rb
spec/unit/config_spec.rb

Currently the semantics for $libdir are that it's an array of paths
that MCollective should search for plugins.  The change we make
here is to make $libdir more generally extend $LOAD_PATH and use
$LOAD_PATH for all plugin loading.
This allows plugins for to be located in gems and for plugin
resolution to be influenced by the RUBYLIB environent variable, or
the ruby -I switch.
In the configuration parser we make the values supplied by the user
be prepended to the ruby $LOAD_PATH.
When loading plugins we now search all of $LOAD_PATH (via
Config.instance.libdir) for ddl searches and plugin loading.

MCO-315 make $libdir prepend values to $LOAD_PATH

---

bin/mcollectived
lib/mcollective/rpc.rb
lib/mcollective/util.rb
spec/unit/util_spec.rb

Here we add a search for readable configuration files, preferring the AIO paths
over the 'classic' /etc/mcollective/{client,server}.cfg paths.
In doing this we refactor config_file_for_user for clarity and add spec tests.

MCO-560 prefer configuration files from AIO paths

---

ext/aio/README.md
ext/aio/common/client.cfg.dist
ext/aio/common/server.cfg.dist
ext/aio/debian/mcollective.default
ext/aio/debian/mcollective.init
ext/aio/redhat/mcollective-systemd.logrotate
ext/aio/redhat/mcollective-sysv.logrotate
ext/aio/redhat/mcollective.init
ext/aio/redhat/mcollective.service
ext/aio/redhat/mcollective.sysconfig

The All-In-One Agent configures MCollective with a specific set of
paths for configurations and pidfiles.
Here we take the work of Geoff Nichols from PR#274 and moves it
into ext/aio, where the All-In-One build process can consume the
files.

MCO-555 Add AIO variants of init and sysconfig files

---

website/changelog.md
website/configure/client.md
website/configure/server.md
website/releasenotes.md

Here we update the changelog, releasenotes, and documentation to reflect the changes in the 2.8.0 release.

MCO-568 2.8.0 release notes and documentation changes

---

bin/mcollectived
lib/mcollective.rb
spec/unit/mcollective/runner_spec.rb

In MCO-580 6bdc58f97 we changed all the autoloads for requires, overlooking
that the mcollective-client gem witholds `lib/mcollective/runner.rb`.  This
causes the gem to to unusable as the require of 'mcollective/runner' can not be
resolved in a clean install.
Here we move the require out to the only users of MCollective::Runner, its unit
tests and the mcollectived script.

MCO-587 fix client gem loading

---

ext/aio/debian/mcollective.init

condrestart was built around some sort of busted lock file
functionality. This changes it to rely on start-stop-daemon to
determine if the process is running or not.

(MCO-591) Fix condrestart on debian for AIO agent

---

ext/redhat/mcollective.service

When starting mcollective under systemd on CentOS 7 I was seeing this
message:
Feb 11 00:35:07 ip-10-169-74-156 systemd: Starting The Marionette Collective...
Feb 11 00:35:08 ip-10-169-74-156 systemd: mcollective.service: Supervising process 6520 which is not our child. We'll most likely not notice when it exits.
Feb 11 00:35:08 ip-10-169-74-156 systemd: Started The Marionette Collective.
This was because mcollectived was configured to daemonize and the
systemd unit file specified a "forking" service.
It is better to not daemonize services under systemd as it enabled them
to be more reliably monitored.
This PR converts the mcollective systemd service to type "simple" and doesn't
daemonize the mcollectived daemon on startup.

Fix warning on mcollective start-up when running under systemd

---

bin/mcollectived
ext/aio/common/client.cfg.dist
ext/aio/common/server.cfg.dist
ext/aio/debian/mcollective.init
ext/aio/redhat/mcollective-systemd.logrotate
ext/aio/redhat/mcollective-sysv.logrotate
ext/aio/redhat/mcollective.init
ext/aio/redhat/mcollective.service
ext/aio/suse/mcollective.init
lib/mcollective/util.rb
spec/unit/mcollective/util_spec.rb

The latest version of the Unified Puppet Agent Layout calls for config files in
/etc/puppetlabs/$project/$project.conf, logfiles in
/var/log/puppetlabs/$project.log, pidfiles in /var/run/puppetlabs/$project.pid,
binaries in /opt/puppetlabs/puppet/bin and user plugins for MCollective in
/opt/puppetlabs/mcollective/plugins.
Here we make those changes.

MCO-594 Update for latest AIO paths

---

website/reference/basic/messageformat.md
website/reference/plugins/aggregate.md

Some of the documentation for extension points refers to core
plugins.  These moved as part of MCO-583 but the documentation was
overlooked.  Here we update those links.

(maint) update plugin paths post MCO-583

---

ext/aio/common/client.cfg.dist

If the middleware is down, or unreachable (which it's very likely to be for
stomp1:6163 as it's just placeholder) the client will just sit and wait which
is a poor first impression.  Add connection_timeout to the example config file,
so a user won't sit wondering why `mco ping` in an unconfigured environment
simply waits.

(maint) specify a default connection_timeout

---

ext/project_data.yaml
lib/mcollective.rb
lib/mcollective/ddl/base.rb
spec/unit/mcollective/ddl/base_spec.rb

Here we change version assignment from a release machinery task to a manual one, for consistency with other PuppetLabs projects.

MCO-617 Assign version in-tree

---

ext/project_data.yaml

As noted by @haus on PR#300, the removal of `update_version_file` also implies
we no longer need the `version_file` key in project_data.
https://github.com/puppetlabs/marionette-collective/pull/300#discussion-diff-25886614

(maint) remove version_file from project_data

---

ext/aio/suse/mcollective.init

Apparently runlevel 4 is not used on SUSE, so we remove
it from Default-Start. We also move runlevel 2 to
Default-Stop for consistency with our puppet packaging.

(RE-3977) Remove runlevel 4 from Default-Start for SUSE

---

Gemfile

As per https://github.com/ahoward/systemu/issues/41 systemu's ruby
support policy is "whatever Ruby version is officially supported
at the point in time of the release"
For 1.8 pin to systemu 2.6.4, which is the last known working version
for 1.8

(maint) pin systemu on ruby 1.8

---

ext/aio/osx/mcollective.plist

This commit adds a launchd plist for use with OSX AIO packaging.

(MCO-646) Add launchd plist for use with OSX AIO

---

bin/mco
lib/mcollective/config.rb

Here we downgrade the warning from pointing to a non-existent libdir to a debug message, and make the error raised by a missing application namecheck the application searched for and the paths searched.

MCO-647 downgrade libdir warning

---

ext/aio/common/client.cfg.dist
ext/aio/common/server.cfg.dist

Here we add the two divergent 'default' libdirs from the pre-aio repathing as
search paths to the example configuration file.  This demonstrates the ability
to consult the classic paths in addition to the new standard pathing.

MCO-641 add the 'classic' libdirs to aio sample config

---

bin/mco

Here we change the exitcode of `mco somecommand` when `somecommand` can not be
found to indicate the error condition of a missing application.

MCO-640 exit nonzero if a command can not be found

---

website/deploy/install.md
website/deploy/middleware/activemq.md

Users reading the documentation have previously been directed to email faq@puppetlabs.com which sends a mass email to everyone on the faq list (which is most people in the company). Fixing this to point to our own documentation alias to cut down on excess emails.

(DOC-2043): change mentions of faq@ to docs@puppetlabs.com

---

acceptance/tests/mco_puppet_powershell.rb

This commit adds an acceptance test to verify that executing
a `mco puppet runonce` where a Windows agent is classified
with an exec resource that uses the powershell provider correctly
executes on the Windows system.
This test is currently expected to fail until MCOP-521 is resolved.
The test assertion is wrapped in an `expect_failure` method to
prevent the test run from turning red until MCOP-521 has been fixed.
At that time, the test will fail and the wrapper can be removed to
flip the result.

(MCOP-521) mco runonce with powershell provider test

---

ext/aio/osx/mcollective.plist

This commit fully qualifies the label in the osx mco plist using the
identifier plus service name.

(RE-5032) fully qualify the label in the osx mco plist

---

ext/aio/solaris/smf/mcollective.xml

This commit adds an smf service file for mcollective, based on the PE
service file with updates for the AIO FS layout.

(MCO-687) Add solaris smf service for mcollective for AIO

---

README
website/deploy/middleware/activemq.md
website/reference/integration/activemq_clusters.md

The Fuse docs have all moved from the fusesource.com domain to be under access.redhat.com. The actual pages seem to have moved around a bit as well. This PR updates the links to the fuse docs. 
It also updates the main URL for mcollective in the README to be http://puppetlabs.com/mcollective as it appears http://marionette-collective.org/ is no longer (or it's temporarily offline perhaps?)

update links to fuse docs - moved under access.redhat.com

---

ext/aio/suse/mcollective.init

In the puppet-agent RPM spec we call the 'condrestart' action from
the %postun on package upgrade. This is currently missing from the
sles/suse init scripts.
This adds 'condrestart' as a synonym for the try-restart action.

(packaging) Add condrestart to suse init script

---

ext/aio/solaris/smf/mcollective.xml

Prior to this commit, mcollective service startup
with the Solaris AIO puppet-agent fails because the
SMF manifest is using the non-AIO path to mcollectived.
This commit updates the Solaris SMF service manifest
to use the correct AIO path to mcollectived.

(maint) Fix Solaris SMF service for mcollective for AIO

---

lib/mcollective.rb
website/changelog.md
website/releasenotes.md

Bump the version and update the changelog and readme for 2.8.6 release

(MCO-726) Prepare for 2.8.6 release

---

website/overview_components.md

Update a link, as well as Markdown and prose styles, in the component overview page.

(docs) Fix link and update styles.

---

ext/build_defaults.yaml

Fedora 20 is EOL, so we shouldn't be building packages for it.

(maint) Remove Fedora 20 from build targets

---

website/reference/plugins/security_aes.md
website/reference/plugins/security_ssl.md

I noticed that both security_ssl.md and security_aes.md had the same
page title.
The aes security plugin is now filed under 'Older and
Non-Recommended Information'
https://github.com/puppetlabs/puppet-docs/blob/master/source/_includes/mcollective_menu.html#L89
As such, I've updated the AES page to more strongly suggest the use of
the SSL plugin.

(docs) Correct AES Security Plugin title

---

lib/mcollective/matcher.rb
spec/unit/mcollective/matcher_spec.rb

In the past when data plugins lookups resolved to false, it was
impossible for us to do a false comparison.
The statement:
```
puppet().enabled=false
```
Would always evaluate to false, even when the statement was translated
into
```
false == false
```
Here we fix the bug and do some light refactoring to #eval_compound_fstatement
while we're there.

(MCO-739) Fix negative data plugin comparisons

---

acceptance/setup/aio/pre-suite/050_Install-activemq.rb

amq version 5.11.1 is no longer available from apache. This
commit updates the version to the latest z release of the 5.11
amq version for installation to test against.

(maint) Update amq version to 5.11.3 for tesing

---

ext/aio/redhat/mcollective-systemd.logrotate

systemctl is either in /bin or /usr/bin depending on whether or not
you're running deb-based systems. Those directories should always be in
your path so there's no need to specify the full path for systemctl.

(MCO-744) Remove full path for systemctl in logrotate

---

.travis.yml

Here we attempt to fixup the issue observed in recent travis-ci builds where
bundler is complaining that PATH contains /tmp/ (which is world-writable) by
switching to the newer container-based infrastructure.

(maint) switch to container-based travis builds

---

lib/mcollective.rb
lib/mcollective/vendor/systemu/lib/systemu.rb
website/changelog.md
website/releasenotes.md

This is the second of two possible 2.8.7 releases (the first being #361)
This does incorporate the changes from #357, in addition to the other fixes currently merged.

WIP - Release 2.8.7 preparations

---

install.rb

Here we define the WINDOWS constant to be FALSE on platforms that it is false
for, so we don't break there.
install.rb:302:in `block in <main>': uninitialized constant WINDOWS (NameError)
from /opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:125:in `chdir'
from /opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:125:in `cd'
from install.rb:293:in `<main>'

(MCO-745) Unbreak install.rb for non-windows platforms

---

ext/windows/mco.bat
install.rb

With the switch over to building puppet-agent for windows with Vanagon,
we need to effectively install mcollective with install.rb. This script
installs mco.bat, which is a wrapper that lets windows handle ruby
scripts. This commit updates mco.bat to use our environment.bat file if
we install it, and to be more in line with the mco.bat file installed
with the puppet-agent package as built by puppet_for_the_win
This takes advantage of `environment.bat` in puppet-agent installed with https://github.com/puppetlabs/puppet-agent/pull/512

(MCO-748) Update mco.bat to reflect current standard

---

ext/build_defaults.yaml

We are no longer using the packaging repo to build mco packages. This
happens as a part of the puppet agent build process. This means we no
longer use the build target definitions stored in ext/build-defaults to
determine what platforms to build mco packages for. However, this is a
tool available for community use. Rather than remove these entries
entirely, we should change them to be only LTS platforms. That way, if a
community member is using this automation, they can easily edit the file
to build the platforms they want. It also helps us when we inevitably
look back at this file and wonder why we have build targets listed that
went EOL many cycles ago.

(MCO-634) Set build defaults to LTS targets only

---

lib/mcollective/unix_daemon.rb
spec/unit/mcollective/unix_daemon_spec.rb

The daemonize_runner was not using an exclusive create when writing its pid
file so you could get into a race condition with SysVInit by running
`service mcollective start & service mcollective start`. This also adds
checking to make sure stale PID files get cleaned up.

(MCO-751) Manage PID files to avoid race conditions on process start

---

ext/aio/debian/mcollective.init
ext/aio/redhat/mcollective.init
ext/aio/suse/mcollective.init

Currently, the init scripts naively assume that the pid directory
exists. This works well enough, assuming puppet starts first after
a reboot and creates the pid dir. This is not always the case.
This updates the init scripts to create the pid directory
if it does not exist.

(MCO-753) The init scripts should not assume the existence of the pid dir

---

Gemfile
lib/mcollective/ssl.rb

Required for Ruby 1.8.7 testing.

(maint) Pin Rake to 10.4, work around Rubocop change

---

acceptance/setup/aio/pre-suite/050_Install-activemq.rb

Before this change, the pre-suite would not install activemq correctly, nor tell you why (version out of date, in this case).  
This change bumps the version, and ensures curl will fail when receiving >400 from the apache servers when fetching activemq.
[skip ci]

(maint) fix activemq install

---

website/deploy/install.md

-   Update Puppet branding and puppetlabs links.
-   Resolve [MCO-384](https://tickets.puppetlabs.com/browse/MCO-384).
-   Align semver description with Puppet's.
-   Replace PE version information with links to the PE and OSS docs that track `puppet-agent` component versions.
-   Remove references to resolved Stomp gem dependency issue.
-   Update case and formatting to current Puppet style guide.
CC @haus

(doc) Update installation document

---

install.rb

puppet-agent carries the batch files for all executables with the new move to
vanagon for windows projects, we will need an option to omit batch file
creation during installation of mco so there are not more than one set of
batch files. So this commit adds a --no-batch-files option for cmake that omits
those files.

(MCO-762) Add --no-batch-files option

---

install.rb

prepare_installation does not depend on any variable definitions before it, so
it needs to be moved to the first action taken in install.rb to avoid
situations where the script is using install options before they are defined

(MCO-763) Move prepare_installation to run first

---

README.md

Updates the link in the README to point to Puppet's marionette
collective docs. The prior link was inactive.
Ticketing can be found in the Maintainers section.

(doc) Update README link for documentation

---

acceptance/config/aio/options.rb
acceptance/setup/aio/pre-suite/070_Install_puppet-agent-plugin.rb

Previously, the acceptance setup installed the puppet-agent plugin from
a hard-coded git repo.  This change allows different versions to be
installed from the (forked) repo.
[skip ci]

(maint) acceptance: allow plugin versioned install

---

install.rb

This cherry-picks https://github.com/puppetlabs/marionette-collective/pull/379 and https://github.com/puppetlabs/marionette-collective/pull/380 to stable.

(MCO-762) Add 'no-batch-files' option to install.rb

---

Gemfile

The Stomp 1.4.1 gem adds fixes for SSL hostname verification

(RE-7302) Update Stomp gem dependency to >= 1.4.1

---

.travis.yml
spec/unit/mcollective/pluginmanager_spec.rb

2.0.0 was end-of-lifed in February, so support latest patches of all
later versions.

(maint) Update Ruby testing to currently supported versions

---

lib/mcollective/application/ping.rb

This is a much more limited alternative to https://github.com/puppetlabs/marionette-collective/pull/397

(MCO-775) Ping application should include discovery_timeout

---

lib/mcollective.rb
website/changelog.md
website/releasenotes.md

Update the version number and changelog for 2.9.1 release.

(maint) Prepare for 2.9.1 release

---

lib/mcollective/application/find.rb
lib/mcollective/application/rpc.rb
lib/mcollective/discovery/stdin.rb
lib/mcollective/rpc/client.rb
lib/mcollective/rpc/helpers.rb
spec/unit/mcollective/rpc/client_spec.rb
spec/unit/mcollective/rpc/helpers_spec.rb
website/reference/basic/basic_cli_usage.md

This enables using Puppet Query output as discovery source for
mcollective
```
puppet query "inventory { facts.os.name = 'CentOS' }"| mco puppet runonce
```
Results from puppet query has to include a certname items.
This also makes the find application STDIN aware and adds a nice
reusable method to do the switch other apps can use who wish to support
this workflow

(MCO-776) Support PQL in STDIN discovery

---

lib/mcollective.rb

This bumps the MCollective version to 2.9.2 following the release of
2.9.1 as part of puppet-agent 1.8.0.

(PA-652) Bump MCollective version to 2.9.2

---

lib/mcollective/client.rb
spec/unit/mcollective/client_spec.rb

The Mcollective client class was previously ignoring the publish_timeout
value when specified in the config file, and by default would wait
forever when unthreaded and would crash when threaded. This commit fixes
this by preferring an explicitly set `publish_timeout` value and then
falling back to the config set value.

(MCO-778) use publish_timeout from config

---

Gemfile

This commit includes a few minor changes:
* Only pull in 'json' gem when running under Ruby 1.8.x
* Pin 'rdoc' to a version compatible with Ruby 1.8.x
* Make gem source configurable via ENV
* Correct Ruby 1.8.x regexes

(maint) Gemfile cleanup

---

lib/mcollective/connector/activemq.rb
lib/mcollective/connector/rabbitmq.rb
spec/unit/mcollective/connector/activemq_spec.rb
spec/unit/mcollective/connector/rabbitmq_spec.rb
website/reference/plugins/connector_activemq.md
website/reference/plugins/connector_rabbitmq.md

Implements the suggestion in MCO-736 to use a single target for all agents in the activemq connector.
We are running a collective of 6165 nodes with this change since a few weeks.
We observe that the number of subscriptions indeed dropped from ~75k to ~20k. 
The brokers are happier and querying the list of subscriptions via JMX is now faster.
```
Best regards    ...Ignacio...
```

(MCO-736) Singletarget

---

lib/mcollective/client.rb
lib/mcollective/rpc/client.rb
lib/mcollective/rpc/stats.rb
spec/unit/mcollective/client_spec.rb
spec/unit/mcollective/rpc/client_spec.rb
spec/unit/mcollective/rpc/stats_spec.rb

Modifies mco to wait for responses from all discovered hosts, rather
than stopping when the expected number of hosts have responded. This
ensures that, if a node doesn't respond to discovery but responds to the
rpc, we don't lose responses from all discovered nodes.
Also update stats to print all responses that came from nodes that did
not respond to discovery. This simplifies debugging issues where nodes
respond unexpectedly, allowing us to identify the nodes behaving
unexpectedly.

(MCO-777) Wait for all expected responses to rpc, report surprises

---

lib/mcollective/client.rb
spec/unit/mcollective/client_spec.rb

The prior commit for MCO-777 introduced a bug when running `mco ping`.
It would always report `The ping application failed to run: undefined
method `>' for []:Array`, as it accepts all results and then times out.
Fix by ensuring we don't attempt to compare an array to an integer.

(MCO-777) Fix `mco ping` breakage from prior commit

---

website/plugin_directory/index.markdown

There was a broken link on the plugin index page; this PR fixes it.

(DOCUMENT-618) broken link on plugin index page

---

acceptance/Gemfile
acceptance/README.md
acceptance/Rakefile
acceptance/files/client.cfg
acceptance/files/windows-client.cfg
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/aio/pre-suite/050_Install-activemq.rb
acceptance/setup/aio/pre-suite/060_Install-mcollective-daemon.rb
acceptance/setup/aio/pre-suite/070_Install_puppet-agent-plugin.rb

This commit updates the acceptance Rakefile to bring the
`ci:test:aio` rake task in parity with the other `puppet-agent`
components. Instructions for using this task have been added to the
`README.md` file. The task relies on a recent version of `beaker`
and `beaker-hostgenerator`.

(MCO-782) Update acceptance Rakefile

---

ext/build_defaults.yaml

Since we've integrated marionette collective into the puppet-agent
package, we do not want to build deb or rpm packages. We only want the
gem and tarball to be created when we kick off our build automation.
However, as there are some community members that use this automation,
we should keep the relics in this file for future reference. That is why
they are only commented out, and not fully removed.

(maint) Do not build debs/rpms

---

acceptance/tests/mco_puppet_batch_count.rb
lib/mcollective/client.rb
spec/unit/mcollective/client_spec.rb
spec/unit/mcollective/rpc/client_spec.rb

It looks like changes introduced in 928ccac63ae2820bc47679264c12e4adf3ba08c6
broke --batch option, because one of stats hash elements is not
initialized as Array and concat function is called on that object which
leads to crash.
This commit will make sure, that unexpectedresponsefrom key is
initialized as Array.
P.S. I think that some unit test case is missing, as they are passing with `--batch` broken.

(MCO-785) Fix regression in --batch option

---

website/deploy/install.md
website/deploy/plugins.md
website/deploy/standard.md

Updates documentation to refer to puppet-agent paths and packaging, and
remove references to deprecated plugin packaging. Plugins are now
recommended to be installed via http://choria.io, or PE.

(DOCUMENT-641) Update documentation for puppet-agent paths, packaging

---

acceptance/Rakefile
spec/unit/mcollective/log_spec.rb

If not specified in acceptance tests, add the mco_master property to the
last agent config. Assume it's an agent-only node.
Also fixes an ordering-dependent issue in spec tests.

(maint) Add mco_master if not specified

---

spec/unit/mcollective/security/psk_spec.rb

When aes_security_spec was loaded before psk_spec, PluginManager would
throw a Runtimeerror that the `security_plugin` was already loaded.
Clear the plugin manager in psk_spec in case aes is loaded first.

(MCO-786) Fix intermittent spec failures

---

acceptance/setup/aio/pre-suite/050_Install-activemq.rb

Uses openjdk 7 on Ubuntu 14.04. openjdk 8 isn't easily available.
[skip ci]

(maint) Fix acceptance setup on Ubuntu 14.04

---

lib/mcollective/client.rb
spec/unit/mcollective/client_spec.rb

This allow client applications that interact with the base M::Client
access to the M::Message object associated with a reply.
These clients are advanced clients such as mco ping where you'd really
would like to know things like network headers and such.
Typical end users interact with mcollective via M::RPC::Client and it's
behaviour has not changed and those users still cannot get access to
this object

(MCO-790) Allow M::Client users to access M::Message

---

acceptance/README.md
acceptance/setup/aio/pre-suite/050_Install-activemq.rb

The original ActiveMQ source only hosted the latest release. Use an
internal mirror of the binaries, with an environment variable -
ACTIVEMQ_SOURCE - for overriding it.
[skip ci]

(maint) Fix acceptance source for ActiveMQ

---

.travis.yml
lib/mcollective/ddl/agentddl.rb
lib/mcollective/rpc/client.rb
lib/mcollective/rpc/helpers.rb
lib/mcollective/rpc/request.rb
lib/mcollective/rpc/result.rb
spec/unit/mcollective/ddl/agentddl_spec.rb
spec/unit/mcollective/rpc/client_spec.rb
spec/unit/mcollective/rpc/request_spec.rb
spec/unit/mcollective/rpc/result_spec.rb

This has the end effect that:
c.get_fact(:fact => "cluster")
is the same as:
c.get_fact("fact" => "cluster")
in the case where the DDL defined the input :fact for the action
:get_fact
Additionally RPC::Request will now intelligently convert request[:foo]
into fetching "foo" from such a request.  We could perhaps munge the
entire incoming request instead of this approach but this seems simpler
to implement
Long term I want to downgrade MCollective network protocols to be JSON
pure to facilitate non Ruby clients and JSON based REST gateways and
just general removal of user supplied YAML.
This changes makes it so that not everyone have to redevelop their DDLs,
Agents and Clients
The one problem case is where someone legit made a input :foo and also
one "foo" on the same action, if all we …

(MCO-799) Consider string and symbol keys equivelant

---

website/deploy/middleware/activemq_keystores.md

Due to a fix in the stomp gem, the ActiveMQ certname must now match the
hostname used to reach it. Update docs to reflect this.

(MCO-771) Update docs around ActiveMQ certname

---

website/reference/basic/configuration.md

rpchelptemplate and helptemplatedir were previously deprecated and are
ignored. Remove them from config docs.

(MCO-737) Remove deprecated/ignored options from config docs

---

acceptance/setup/aio/pre-suite/060_Install-mcollective-daemon.rb
ext/aio/common/server.cfg.dist
ext/aio/redhat/mcollective-systemd.logrotate
ext/aio/redhat/mcollective-sysv.logrotate
lib/mcollective/audit/logfile.rb
spec/unit/mcollective/audit/logfile_spec.rb
website/deploy/standard.md
website/simplerpc/auditing.md

This is related to the proposed change in https://github.com/puppetlabs/puppet-specifications/pull/89
This updates the log configuration and logrotate scripts to point to the
new log location in /var/log/puppetlabs/mcollective
Replaces https://github.com/puppetlabs/marionette-collective/pull/410.

(MCO-783) Update mcollective log directory in the aio package

---

lib/mcollective/monkey_patches.rb

ly, we appended "!SSLv2" to the SSLContext
DEFAULT_PARAMS[:ciphers] to ensure that mcollective never uses SSLv2,
either from our http client or when using open-uri. However, ruby 2.4
only defines the `:ciphers` array if using openssl < 1.1.0[1]. As a
result, mcollective running on newer systems would hard fail.
Check existence of array before trying to append to it.
[1] ruby/ruby@c9dc016#diff-8406e11e4a42f9de6badcd0f6a6c4262R33

(MCO-804) Skip cipher monkey patch on ruby 2.4+

---

website/deploy/middleware/activemq.md
website/reference/integration/activemq_clusters.md

Fuse, RedHat's commercialized ActiveMQ broker, seems to be gone and somewhat
forgotten, so we should no longer link to it.
When this is merged, please resolve [DOC-1251](https://tickets.puppetlabs.com/browse/DOC-1251).

(docs) Remove links to the Fuse broker documentation

---

acceptance/setup/aio/pre-suite/060_Install-mcollective-daemon.rb

The prior commit for MCO-783 moved the Windows log location as well,
which was not intended. Fix so only the *nix location is modified in
testing.

(MCO-783) Correct Windows log location

---

acceptance/README.md
acceptance/setup/aio/pre-suite/050_Install-activemq.rb

The Oracle JDK source only hosts the latest release. To prevent the
need to often update the test, use an internal mirror of the Windows
binaries, with an environment variable - JDK_SOURCE - for overriding it.
Other platforms will continue to be managed via their respective
package managers.
[skip ci]

(MCO-808) Fix acceptance source for JDK on Windows

---

acceptance/setup/aio/pre-suite/060_Install-mcollective-daemon.rb
acceptance/tests/mco_reconnect.rb

Adds a test ensuring mcollective servers will reconnect to ActiveMQ
after a hard connection loss. Simulates lost connections by blocking
ports via the firewall.
Depends on https://github.com/puppetlabs/puppet-agent/pull/1071.

(maint) Add test for PA-1168

---

Gemfile
README.md

Stomp 1.4.4 incorporates two bug fixes we've been carrying in
puppet-agent packaging. 1.4 also included a rewrite that broke SSL that
has now been fixed with this release.
Add instructions for running spec and acceptance tests, and setting up a
local environment.

Bump stomp dependency to 1.4.4 and add dev instructions

---

acceptance/tests/mco_puppet_exec.rb

PE-14681 and MODULES-3125 identified issues running commands via
Puppet exec from other service agents. These issues led to PUP-6675:
selinux prevents processes from writing to files in /tmp if they
don't have a reason to do so. The Puppet service selinux policy
appears to exempt this, but other services that invoke Puppet - such
as mcollective - aren't configured that way and cause silent exec
failures.
PUP-6675 fixes this issue. We add an acceptance test to ensure that it
doesn't recur in pxp-agent.

(maint) Add testing around exec via Puppet

---

acceptance/tests/mco_puppet_exec.rb

Cygwin is installed at C:/cygwin, not C:/cygwin32.
[skip ci]

(maint) Fix the test on win-10-ent-i386

---

lib/mcollective/rpc/client.rb
spec/unit/mcollective/rpc/client_spec.rb

When JSON serializers are enabled the result needs to be processed by
the rpc_result_from_reply method to be processed into the right format
based on the DDL
The methods that determined the reply status though acted on the
unconverted raw data and so would incorrectly determine the reply failed
when it did not

(MCO-815) Correctly determine reply status in all modes

---

lib/mcollective/rpc/stats.rb

Instead of the extremely slow looping over every result use the built in
array maths to calculate nodes that did not respond and unexpected
responses

(MCO-818) Use native array maths to calculate responses

---

lib/mcollective/config.rb
lib/mcollective/rpc/client.rb
spec/unit/mcollective/rpc/client_spec.rb
website/reference/basic/configuration.md

In order to allow admins to protect themselves from accidents by users
who forget to specify batch options this allows the admins to configure
`default_batch_size` and `default_batch_sleep_time` in the client config
which would then always be active when not otherwise specified

(MCO-820) Allow default batch options to be set

---

ext/aio/redhat/mcollective.service
ext/redhat/mcollective.service

Since mcollective is part of puppet-agent packaging, upgrading that
package over an mcollective plugin is tricky. Previously the mcollective
systemd service was currently configured in a way that broke that,
because it killed the entire process tree when stopping as part of the
upgrade.
Set `KillMode=process` for the systemd service (similar to how Puppet
and PXP Agent are configured) so that it can be restarted during the
upgrade without killing the upgrade itself.

(MCO-816) Allow upgrading puppet-agent with mcollective

---

acceptance/lib/puppet/acceptance/install_utils.rb

This commit changes the name of the nightlies server to the actual hostname so that when we remove the 'nightlies' cname (to use for *new* nightlies), tests won't break. THIS SHOULD NOT BE PERMANENT (see RE-10231).

(maint) Update acceptance tests that reference nightlies

---

lib/mcollective.rb

This is a preemptive reported version bump in advance of the puppet agent 5.5.0 release.

(packaging) Update reported version to 2.12.0

---

lib/mcollective.rb
lib/mcollective/logger/file_logger.rb
spec/unit/mcollective/logger/file_logger_spec.rb

This commit updates the format used by the File_logger to include the offset
from UTC in the timestamp added to the log messages. This context helps with
troubleshooting issues that arise when the client, server, and broker are
operating in different time zones.

(MCO-832) Include offset from UTC in log messages

---

lib/mcollective/connector/activemq.rb
spec/unit/mcollective/connector/activemq_spec.rb

We raise an error message if a STOMP frame with a type other than MESSAGE is
received. Details about the frame are logged at debug level, which means they
never actually make it into the logs on a normal system. The content of these
frames can include important information about broker health. This commit
increases the log level from DEBUG to WARN so that this information is captured
alongside the error message.

(MCO-803) Log unexpected STOMP frames at WARN level

---

lib/mcollective/facts/yaml_facts.rb

If YAML.safe_load is in use, we need to explicity enable aliases. This
is needed for example by choria-mcollective which is creating
aliases for `libdir`.

(MCO-833) Fix loading facts when YAML file contains aliases

---

lib/mcollective/matcher/scanner.rb
spec/unit/mcollective/matcher/scanner_spec.rb

Allows function arguments to be unquoted, as in `fact(os.family)`.

(MCO-817) Allow unquoted function arguments

---

.travis.yml

To bump to newer versions of rake, we need to stop using it to run rspec
because rspec 2 and rake 12 are incompatible.

(maint) Use rspec spec in Travis
